import {ACTIONS, ADDITIONAL, BASE_API_URL, RESOURCES} from "../baseUrls";


export const BASE_URLS_CART = {
    GET_CART: `${BASE_API_URL}${RESOURCES.CART}${ACTIONS.LIST}`,
    REGISTER_CART: `${BASE_API_URL}${RESOURCES.CART}${ACTIONS.REGISTER}`,
    UPDATE_CART: `${BASE_API_URL}${RESOURCES.CART}${ACTIONS.UPDATE}`,
    DELETE_CART: `${BASE_API_URL}${RESOURCES.CART}${ACTIONS.DELETE}`,
    DELETE_CART_PRODUCT: `${BASE_API_URL}${RESOURCES.CART}${ADDITIONAL.DELETE_CART_PRODUCT}`,
};