# Generated by Django 5.1.1 on 2025-01-05 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='description',
            new_name='user_agent',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='action',
        ),
        migrations.AddField(
            model_name='audit',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
