# Generated by Django 5.1.1 on 2025-01-19 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_rename_timestamp_audit_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audit',
        ),
    ]
