# Generated by Django 5.1.1 on 2025-07-15 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Imagen')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'Producto en Carrito',
                'verbose_name_plural': 'Productos en Carrito',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='store.CartProduct', to='store.product', verbose_name='Productos'),
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('name', models.TextField(verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('industry', models.TextField(choices=[('AGRICULTURE', 'Agricultura'), ('AUTOMOTIVE', 'Automotriz'), ('BIOTECHNOLOGY', 'Biotecnología'), ('CONSTRUCTION', 'Construcción'), ('EDUCATION', 'Educación'), ('ENTERTAINMENT', 'Entretenimiento'), ('FINANCE', 'Finanzas'), ('FOOD', 'Alimentos'), ('TECHNOLOGY', 'Tecnología'), ('WELDING', 'Soldadura'), ('HAIRDRESSING', 'Peluquería'), ('CLOTHING_SALES', 'Venta de ropa'), ('GENERAL', 'Otros')], verbose_name='Industria')),
                ('icon', models.TextField(blank=True, choices=[('GiPlantVine', 'Agricultura'), ('FaCarSide', 'Automotriz'), ('GiMicroscope', 'Biotecnología'), ('FaHardHat', 'Construcción'), ('FaGraduationCap', 'Educación'), ('MdTheaterComedy', 'Entretenimiento'), ('FaMoneyBillWave', 'Finanzas'), ('GiForkKnifeSpoon', 'Alimentos'), ('FaMicrochip', 'Tecnología'), ('GiWeldingTorch', 'Soldadura'), ('FaCut', 'Peluquería'), ('FaTshirt', 'Venta de ropa'), ('FaBoxes', 'Otro')], verbose_name='Icon')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startups', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Startup',
                'verbose_name_plural': 'Startups',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='start_up',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.startup', verbose_name='Startup'),
        ),
        migrations.AddField(
            model_name='category',
            name='start_up',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.startup', verbose_name='Startup'),
        ),
    ]
