import {ACTIONS, BASE_API_URL, RESOURCES} from "../baseUrls";


export const BASE_URLS_PRODUCT = {
    REGISTER_PRODUCT: `${RESOURCES.PRODUCT}${ACTIONS.REGISTER}`,
    GET_PRODUCT: `${BASE_API_URL}${RESOURCES.PRODUCT}${ACTIONS.LIST}`,
    DELETE_PRODUCT: `${BASE_API_URL}${RESOURCES.PRODUCT}${ACTIONS.DELETE}`,
    UPDATE_PRODUCT: `${BASE_API_URL}${RESOURCES.PRODUCT}${ACTIONS.UPDATE}`,
    DETAIL_PRODUCT: `${BASE_API_URL}${RESOURCES.PRODUCT}${ACTIONS.DETAIL}`,
}