import {ACTIONS, BASE_API_URL, RESOURCES} from "../../../core/constants/baseUrls";

export const ORDER_ENDPOINTS = {
    REGISTER_ORDER: `${BASE_API_URL}${RESOURCES.ORDER}${ACTIONS.REGISTER}`,
    GET_ORDERS: `${BASE_API_URL}${RESOURCES.ORDER}${ACTIONS.LIST}`,
    GET_ORDER_DETAIL: `${BASE_API_URL}${RESOURCES.ORDER}${ACTIONS.DETAIL}`,
}