import {ACTIONS, BASE_API_URL, RESOURCES} from "../../../../core/constants/baseUrls";


export const USER_ENDPOINTS  = {
    REGISTER_USER: `${BASE_API_URL}${RESOURCES.USER}${ACTIONS.REGISTER}`,
    UPDATE_USER: `${BASE_API_URL}${RESOURCES.USER}${ACTIONS.UPDATE}`,
    DELETE_USER: `${BASE_API_URL}${RESOURCES.USER}${ACTIONS.DELETE}`,
}