import {BASE_API_URL, RESOURCES, ACTIONS} from "../baseUrls";


export const BASE_URLS_CATEGORY = {
    REGISTER_CATEGORY: `${RESOURCES.CATEGORY}register/`,
    GET_CATEGORY: `${BASE_API_URL}${RESOURCES.CATEGORY}list/`,
    UPDATE_CATEGORY: `${BASE_API_URL}${RESOURCES.CATEGORY}${ACTIONS.UPDATE}`,
    DELETE_CATEGORY: `${BASE_API_URL}${RESOURCES.CATEGORY}${ACTIONS.DELETE}`,
};