import {ACTIONS, BASE_API_URL, RESOURCES} from "../baseUrls";

let ICONS = "icons/"

export const BASE_URLS_STARTUP = {
    GET_STARTUP: `${BASE_API_URL}${RESOURCES.STARTUP}${ACTIONS.LIST}`,
    REGISTER_STARTUP: `${RESOURCES.STARTUP}${ACTIONS.REGISTER}`,
    UPDATE_STARTUP: `${BASE_API_URL}${RESOURCES.STARTUP}${ACTIONS.UPDATE}`,
    DELETE_STARTUP: `${BASE_API_URL}${RESOURCES.STARTUP}${ACTIONS.DELETE}`,
    STARTUP_ICONS: `${BASE_API_URL}${RESOURCES.STARTUP}${ICONS}`,
}