import { BASE_API_URL, RESOURCES, ACTIONS } from "../baseUrls";

export const BASE_URLS_STARTUP ={
    GET_STARTUP: `${BASE_API_URL}${RESOURCES.STARTUP}list/`,

    REGISTER_STARTUP: `${RESOURCES.STARTUP}register/`,
    UPDATE_STARTUP: `${BASE_API_URL}${RESOURCES.STARTUP}${ACTIONS.UPDATE}`,
    DELETE_STARTUP: `${BASE_API_URL}${RESOURCES.STARTUP}${ACTIONS.DELETE}`,
}