import {ACTIONS, BASE_API_URL, RESOURCES} from "../baseUrls";


export const BASE_URLS_INDUSTRY = {
    GET_INDUSTRY: `${BASE_API_URL}${RESOURCES.INDUSTRY}${ACTIONS.LIST}`,
    GET_USER_INDUSTRY: `${BASE_API_URL}${RESOURCES.INDUSTRY}${ACTIONS.USER_INDUSTRY}`,

}