import {ACTIONS, BASE_API_URL, RESOURCES} from "../baseUrls";

export const BASE_URLS_ORDER = {
    REGISTER_ORDER: `${BASE_API_URL}${RESOURCES.ORDER}${ACTIONS.REGISTER}`,
    GET_ORDERS: `${BASE_API_URL}${RESOURCES.ORDER}${ACTIONS.LIST}`,
    GET_ORDER_DETAIL: `${BASE_API_URL}${RESOURCES.ORDER}${ACTIONS.DETAIL}`,
}