import { BASE_API_URL, RESOURCES, ACTIONS } from "../baseUrls";


export const BASE_URLS_PRODUCT ={
    REGISTER_PRODUCT: `${RESOURCES.PRODUCT}register/`,
    GET_PRODUCT: `${BASE_API_URL}${RESOURCES.PRODUCT}list/`,
    DELETE_PRODUCT: `${BASE_API_URL}${RESOURCES.PRODUCT}${ACTIONS.DELETE}`,
    UPDATE_PRODUCT: `${BASE_API_URL}${RESOURCES.PRODUCT}${ACTIONS.UPDATE}`,
    DETAIL_PRODUCT: `${BASE_API_URL}${RESOURCES.PRODUCT}${ACTIONS.DETAIL}`,
}