import {ACTIONS, BASE_API_URL, RESOURCES} from "../../../core/constants/baseUrls";

let ICONS = "icons/"
let GET_ALL_STARTUPS = 'all-startups/';

export const BASE_URLS_STARTUP = {
    GET_STARTUP: `${BASE_API_URL}${RESOURCES.STARTUP}${ACTIONS.LIST}`,
    REGISTER_STARTUP: `${RESOURCES.STARTUP}${ACTIONS.REGISTER}`,
    UPDATE_STARTUP: `${BASE_API_URL}${RESOURCES.STARTUP}${ACTIONS.UPDATE}`,
    DELETE_STARTUP: `${BASE_API_URL}${RESOURCES.STARTUP}${ACTIONS.DELETE}`,
    STARTUP_ICONS: `${BASE_API_URL}${RESOURCES.STARTUP}${ICONS}`,
    GET_ALL_STARTUPS: `${BASE_API_URL}${RESOURCES.STARTUP}${GET_ALL_STARTUPS}`,
}