import {BASE_API_URL, RESOURCES, ACTIONS} from "../../../core/constants/baseUrls";


export const CATEGORY_ENDPOINT = {
    REGISTER_CATEGORY: `${RESOURCES.CATEGORY}${ACTIONS.REGISTER}`,
    GET_CATEGORY: `${BASE_API_URL}${RESOURCES.CATEGORY}${ACTIONS.LIST}`,
    UPDATE_CATEGORY: `${BASE_API_URL}${RESOURCES.CATEGORY}${ACTIONS.UPDATE}`,
    DELETE_CATEGORY: `${BASE_API_URL}${RESOURCES.CATEGORY}${ACTIONS.DELETE}`,
};