import {ACTIONS, BASE_API_URL, RESOURCES} from "../../../../core/constants/baseUrls";


export const INDUSTRY_ENDPOINTS = {
    GET_INDUSTRY: `${BASE_API_URL}${RESOURCES.INDUSTRY}${ACTIONS.LIST}`,
    GET_USER_INDUSTRY: `${BASE_API_URL}${RESOURCES.INDUSTRY}${ACTIONS.USER_INDUSTRY}`,

}