import {ACTIONS, BASE_API_URL, RESOURCES} from "../baseUrls";


export const BASE_URLS_USER = {
    REGISTER_USER: `${BASE_API_URL}${RESOURCES.USER}${ACTIONS.REGISTER}`,
    UPDATE_USER: `${BASE_API_URL}${RESOURCES.USER}${ACTIONS.UPDATE}`,
    DELETE_USER: `${BASE_API_URL}${RESOURCES.USER}${ACTIONS.DELETE}`,
}